language: python
dist: trusty
# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required

env:
  matrix:
    - OMERO_VERSION=5.1
    - OMERO_VERSION=5.2
    - OMERO_VERSION=5.3

before_install:
  # The installation of the python dependencies must be done in that level for now
  # otherwise they are not available in the containers,
  # see https://github.com/travis-ci/travis-ci/issues/8048
  # Changing the value for sudo will also need to be reviewed at the same time
  # This will need to be reviewed when the issue above is fixed
  - export PATH=/usr/bin/:$PATH
  - sudo apt-get install -y zeroc-ice35
  - pip install omego
  - omego download --ice 3.5 --release ${OMERO_VERSION} py
  - rm OMERO.py*.zip
  - mv OMERO.py* /tmp/OMERO.py

script:
    - python setup.py flake8
    - PYTHONPATH=/tmp/OMERO.py/lib/python python setup.py test --pytest-args='-v -v'
    - sudo python setup.py sdist install --record files.txt
    - PYTHONPATH=/tmp/OMERO.py/lib/python python -c 'import omero.clients; import omero_marshal.encode'
    - cat files.txt | xargs sudo rm -rf
    - sudo python setup.py bdist_egg
    - easy_install dist/*.egg
    - PYTHONPATH=/tmp/OMERO.py/lib/python python -c 'import omero.clients; import omero_marshal.encode'
